version: '3.1'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    platform: linux/arm64
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native client interface
    volumes:
      - clickhouse_data:/Volumes/black/clickhouse
    restart: unless-stopped
    environment:
      CLICKHOUSE_USER: root
      CLICKHOUSE_PASSWORD: javac

volumes:
  clickhouse_data:
    driver: local