package tests;

import com.balatro.api.Balatro;
import com.balatro.cache.CompressedData;
import com.balatro.cache.JokerFile;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class Differentiator {

    public static void main(String[] args) {
        List<CompressedData> compressedData = JokerFile.readCompressedFile(new File("canio.jkr"));

        System.out.println("Number of seeds: " + compressedData.size());

        var first = compressedData.getFirst();

        var run = Balatro.builder(first.getSeed(), 8)
                .analyzeAll();

        var expected = new CompressedData(run);

        if (expected.equals(first)) {
            throw new IllegalStateException("First seed is not the same as the one generated by the game");
        }

        var count = 0;
        List<CompressedData> invalidSeeds = new ArrayList<>();
        for (int i = 1; i < compressedData.size(); i++) {
            var s = compressedData.get(i);

            try {
                s.getSeed();
            } catch (Exception e) {
                System.out.println("Seed " + i + " is not valid");
                count++;
                invalidSeeds.add(s);
            }
        }

        for (CompressedData invalidSeed : invalidSeeds) {
            compressedData.remove(invalidSeed);
        }

        for (int i = 0; i < compressedData.size(); i++) {
            for (int j = i; j < compressedData.size(); j++) {
                if (i == j) continue;

                var x = compressedData.get(i);
                var y = compressedData.get(j);

                if (x.equals(y)) {
                    System.out.println("Seed " + i + " and " + j + " are the same");
                }
            }
        }
    }
}
